name: Build And Test

on: [push]

env:
  CARGO_TERM_COLOR: always
  CARGOFLAGS: --workspace --all-targets --all-features --release
  # Use conservative CPU features for CI compatibility (no AVX-512)
  RUSTFLAGS: -C target-cpu=x86-64-v2

jobs:
  build:
    name: Compile code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install SP1 toolchain
        run: |
          curl -L https://sp1up.succinct.xyz | bash
          echo "$HOME/.sp1/bin" >> $GITHUB_PATH
          $HOME/.sp1/bin/sp1up
          $HOME/.sp1/bin/cargo-prove prove --version

      - name: Save build artifacts
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "build"

      - name: Compile
        run: cargo build $CARGOFLAGS --verbose

  test:
    name: Test code
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Install SP1 toolchain
        run: |
          curl -L https://sp1up.succinct.xyz | bash
          echo "$HOME/.sp1/bin" >> $GITHUB_PATH
          $HOME/.sp1/bin/sp1up

      - name: Restore cached build artifacts
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "build"

      - name: Run tests
        run: cargo test $CARGOFLAGS
