name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: read

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  fmt:
    name: rustfmt
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: rustfmt

      - name: Run fmt
        run: cargo +nightly fmt --all -- --check

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    needs: fmt

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: "1.90.0"
          components: clippy

      - name: Install SP1 system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev curl ca-certificates

      - name: Install Go (for SP1 native gnark)
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache-dependency-path: "**/go.sum"

      - name: Restore caches
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.sp1
            target
          key: ${{ runner.os }}-clippy-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-clippy-

      - name: Install SP1up CLI
        run: |
          curl -L https://sp1up.succinct.xyz | bash -s -- -y
          echo "$HOME/.sp1/bin" >> "$GITHUB_PATH"

      - name: Setup SP1 toolchain
        run: |
          sp1up
          rustc +succinct --version

      - name: Run clippy
        run: cargo clippy --locked --workspace --all-targets --all-features -- -D warnings

  build-and-test:
    name: build-and-test
    runs-on: ubuntu-latest
    needs:
      - fmt
      - clippy

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: "1.90.0"

      - name: Install SP1 system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev curl ca-certificates

      - name: Install Go (for SP1 native gnark)
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache-dependency-path: "**/go.sum"

      - name: Restore caches
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.sp1
            target
          key: ${{ runner.os }}-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Install SP1up CLI
        run: |
          curl -L https://sp1up.succinct.xyz | bash -s -- -y
          echo "$HOME/.sp1/bin" >> "$GITHUB_PATH"

      - name: Setup SP1 toolchain
        run: |
          sp1up
          rustc +succinct --version

      - name: Build
        run: cargo build --locked --workspace --all-targets

      - name: Test
        run: cargo test --locked --workspace --all-targets -- --nocapture
